### ISSUE TITLE
Cannot sign in on Safari

### ISSUE THREAD

**Issue by jwngr** [codeapprove/feedback#112]
Trying to use CA in Safari just leads to an infinite loader. Some errors in the console:

![Screenshot - 2024-04-16 at 11 -40-31@2x](https://github.com/codeapprove/feedback/assets/4149793/3a8d0770-1ac7-4bb3-b63c-dc82e1a3178b)

**Comment by samatcodeapprove** [comment]
Hmm interesting. I was not able to reproduce this myself so I'll have to do some digging to see why it's happening to you.

**Comment by samatcodeapprove** [comment]
A few similar issues on the Firebase SDK GitHub:

- https://github.com/firebase/firebase-js-sdk/issues/7888
- https://github.com/firebase/firebase-js-sdk/issues/8034

Although I am not even sure if that error is the core of the issue here because CodeApprove does not actually use Remote Config at all. I don't see any errors from the endpoint which checks email addresses to allow sign in (I see that's what you're doing in your screenshot) so that's not it either.

Are other people at Shortwave able to reproduce this, or is it just affecting you so far?

**Comment by jwngr** [comment]
Was able to get this working after a hard refresh

**Comment by samatcodeapprove** [comment]
@jwngr thanks for confirming. If this pops up again let me know. Of course Sentry will let me know too, but would be good to know it's you because a lot of times I get IndexedDB errors from scraper bots and ignore them.
