### ISSUE TITLE
CodeApprove renders input elements in comments

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#97]
I'm not sure if this works for any other HTML elements, but we discovered this by accident. If a CodeApprove comment includes `<input>`, CodeApprove renders an input element in the comment, which is unexpected. I was expecting to see it stay in text form because the discussion was about an `input` HTML element.

![image](https://user-images.githubusercontent.com/7783288/235459825-ae384634-549a-4dad-867c-1e3ac4f80099.png)

![image](https://user-images.githubusercontent.com/7783288/235459912-2004346d-7830-4a43-9aab-5092abb2afe8.png)

The workaround is to backtick the `<input>` so that CodeApprove doesn't try to render it as HTML.

**Comment by samatcodeapprove** [comment]
@mtlynch ah yeah this makes sense, since that's a rich markdown input. Technically that's "correct" but realistically nobody is trying to write an input in a comment (as opposed to things like `span`, `ul`, `b`, `img` etc which should be treated as HTML). I should adjust the HTML sanitizer to have a stricter set of allowed elements.

**Comment by samatcodeapprove** [comment]
Deploying a fix for this now.
